// GENERATED FILE - DO NOT EDIT.
// Generated by scripts/generate.py using data from errata/*.yaml
//
// Copyright 2023 Google LLC
//
// SPDX-License-Identifier: Apache-2.0

#ifndef GOOGLE_VULKAN_ERRATA_H
#define GOOGLE_VULKAN_ERRATA_H

#include <stdbool.h>
#include <vulkan/vulkan_core.h>

namespace vulkan_errata {


typedef enum class Platform
{
    Android,
    ChromeOS,
    Fuchsia,
    IOS,
    Linux,
    Mac,
    Windows,
} Platform;

typedef struct KnownIssue
{
    // Whether the current platform is affected by the issue
    bool affected;
    // What the snake_case name of the issue is
    const char *name;
    // What the camelCase name of the issue is
    const char *camelCaseName;
    // Short description of the issue
    const char *description;
    // The condition to detect the issue
    const char *condition;
} KnownIssue;

typedef struct KnownIssues
{
    struct KnownIssue flipped_present_region_rectangle_origin;
    struct KnownIssue get_query_result_does_not_wait_for_completion;
    struct KnownIssue incorrect_dynamic_stencil_write_mask_state;
    struct KnownIssue point_size_not_clamped;
} KnownIssues;

// Automatically fill in the struct fields based on platform, device and driver properties.
VkResult GetKnownIssues(
    Platform platform,
    const VkPhysicalDeviceProperties *device,
    const VkPhysicalDeviceDriverProperties *driver,
    KnownIssues *issues);


}  // namespace vulkan_errata

#endif  // GOOGLE_VULKAN_ERRATA_H
