// GENERATED FILE - DO NOT EDIT.
// Generated by scripts/generate.py using data from errata/*.yaml
//
// Copyright 2023 Google LLC
//
// SPDX-License-Identifier: Apache-2.0

#ifndef GOOGLE_VULKAN_ERRATA_H
#define GOOGLE_VULKAN_ERRATA_H

#include <stdbool.h>
#include <vulkan/vulkan_core.h>


#ifdef __cplusplus
extern "C" {
#endif

typedef enum  VulkanErrataPlatform
{
    VulkanErrataPlatformAndroid,
    VulkanErrataPlatformChromeOS,
    VulkanErrataPlatformFuchsia,
    VulkanErrataPlatformIOS,
    VulkanErrataPlatformLinux,
    VulkanErrataPlatformMac,
    VulkanErrataPlatformWindows,
} VulkanErrataPlatform;

typedef struct VulkanErrataKnownIssue
{
    // Whether the current platform is affected by the issue
    bool affected;
    // What the snake_case name of the issue is
    const char *name;
    // What the camelCase name of the issue is
    const char *camelCaseName;
    // Short description of the issue
    const char *description;
    // The condition to detect the issue
    const char *condition;
} VulkanErrataKnownIssue;

typedef struct VulkanErrataKnownIssues
{
    struct VulkanErrataKnownIssue incorrect_dynamic_stencil_write_mask_state;
} VulkanErrataKnownIssues;

// Automatically fill in the struct fields based on platform, device and driver properties.
VkResult vulkanErrataGetKnownIssues(
    VulkanErrataPlatform platform,
    const VkPhysicalDeviceProperties *device,
    const VkPhysicalDeviceDriverProperties *driver,
    VulkanErrataKnownIssues *issues);

#ifdef __cplusplus
}
#endif


#endif  // GOOGLE_VULKAN_ERRATA_H
